#!/bin/sh
# generated by jev-ios init
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"
if [ -n "${SIMULATOR_UDID:-}" ]; then
  set -- --udid "$SIMULATOR_UDID" "$@"
else
  set -- --devices auto "$@"
fi
exec jev-ios matrix --suite .jev-ios/suite.json --mode shard --parallel 1 "$@"
